/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.58
 * Generated at: 2020-11-26 03:52:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import func.funct;
import bean.SachBean;
import bean.loaiBean;
import java.util.ArrayList;
import bo.loaiBo;
import bo.cartBo;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/navbar.jsp", Long.valueOf(1606360092065L));
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1606233856647L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("func.funct");
    _jspx_imports_classes.add("bo.loaiBo");
    _jspx_imports_classes.add("bo.cartBo");
    _jspx_imports_classes.add("bean.SachBean");
    _jspx_imports_classes.add("bean.loaiBean");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://fonts.googleapis.com/css2?family=Poppins&display=swap\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<script src=\"https://kit.fontawesome.com/7e31e7a48c.js\"\r\n");
      out.write("\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/Style1.css\">\r\n");
      out.write("<title>Surface1989</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"bg-light\">\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://fonts.googleapis.com/css2?family=Poppins&display=swap\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<script src=\"https://kit.fontawesome.com/7e31e7a48c.js\"\r\n");
      out.write("\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"bootstrap/css/bootstrap.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"bootstrap/css/bootstrap.min.css\">\r\n");
      out.write("<link href=\"fontawesome/css/fontawesome.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"fontawesome/css/brands.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"fontawesome/css/solid.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"css/Style1.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"css/Nav.css\" rel=\"stylesheet\">\r\n");
      out.write("<title>Bootstrap</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");

		String id = null;
		if (request.getAttribute("id") != null) {
			id = request.getAttribute("id").toString();
		}
	
      out.write("\r\n");
      out.write("\t<nav\r\n");
      out.write("\t\tclass=\"navbar navbar-expand-lg navbar-dark light bg-dark  text-light sticky\">\r\n");
      out.write("\t\t<a class=\"navbar-brand text-danger mr-5\" href=\"home\"><i><h4>Surface1989</h4></i></a>\r\n");
      out.write("\t\t<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\"\r\n");
      out.write("\t\t\tdata-target=\"#navbarTogglerDemo02\"\r\n");
      out.write("\t\t\taria-controls=\"navbarTogglerDemo02\" aria-expanded=\"false\"\r\n");
      out.write("\t\t\taria-label=\"Toggle navigation\">\r\n");
      out.write("\t\t\t<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("\t\t</button>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"collapse navbar-collapse\" id=\"navbarTogglerDemo02\">\r\n");
      out.write("\t\t\t<ul class=\"navbar-nav mr-auto mt-2 mt-lg-0\">\r\n");
      out.write("\t\t\t\t<li class=\"nav-item mr-2\"><a class=\"nav-link\" href=\"home\">Home\r\n");
      out.write("\t\t\t\t\t\t<span class=\"sr-only\">(current)</span>\r\n");
      out.write("\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"nav-item mr-2\"><a class=\"nav-link\" href=\"#\">Bán\r\n");
      out.write("\t\t\t\t\t\tchạy</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"nav-item mr-2\"><a class=\"nav-link\" href=\"#\">Tác\r\n");
      out.write("\t\t\t\t\t\tgiả</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"nav-item mr-2\"><a class=\"nav-link\" href=\"#\">NXB</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"nav-item mr-2\"><a class=\"nav-link\" href=\"#\">Liên\r\n");
      out.write("\t\t\t\t\t\thệ</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t<form action=\"search\" class=\"mr-5\" method=\"get\" style=\"width: 30%;\">\r\n");
      out.write("\t\t\t\t");

					String key = "Nhập tên sách cần tìm kiếm";
					if (request.getAttribute("key") != null) {
						key = request.getAttribute("key").toString();
					}
				
      out.write("\r\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"key\" class=\"input\" placeholder=\"");
      out.print(key);
      out.write("\">\r\n");
      out.write("\t\t\t\t<button class=\"button text-danger mr-1\" type=\"submit\">\r\n");
      out.write("\t\t\t\t\t<i class=\"fas fa-search\" style=\"font-size: 20px;\"></i>\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t<ul class=\"nav navbar-nav navbar-right mr-3\">\r\n");
      out.write("\t\t\t\t");

					HttpSession ss = request.getSession();
					int n = 0;
					if (session.getAttribute("carts") != null) {
						cartBo carts = (cartBo) session.getAttribute("carts");
						n = carts.tongSL();
					}
				
      out.write("\r\n");
      out.write("\t\t\t\t<li class=\"mr-4 smaller cursor\"><a class=\"a\" href=\"listcart\"><i\r\n");
      out.write("\t\t\t\t\t\tclass=\"fas fa-cart-arrow-down text-danger font-size\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"font-size: 20px;\"></i><span class=\"bg-success mr-1\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"padding: .15rem; border-radius: 10px; font-size: 10px;\">");
      out.print(n);
      out.write("</span>&nbsp;Giỏ\r\n");
      out.write("\t\t\t\t\t\thàng</a></li>\r\n");
      out.write("\t\t\t\t");

					if (id == null) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<li class=\"smaller cursor mr-1 ml-4\"><a href=\"login\" class=\"a\"><i\r\n");
      out.write("\t\t\t\t\t\tclass=\"fas fa-sign-in-alt mr-1 text-danger\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"font-size: 20px;\"></i>Đăng nhập</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"smaller cursor\"><a href=\"sign-in\" class=\"a\"><i\r\n");
      out.write("\t\t\t\t\t\tclass=\"fas fa-users ml-2 mr-1 text-danger\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"font-size: 20px;\"></i>Đăng ký</a> ");

 	} else {
 
      out.write("\r\n");
      out.write("\t\t\t\t<li class=\"ml-5\"><p class=\" m-0 text-success\">\r\n");
      out.write("\t\t\t\t\t\tHi!\r\n");
      out.write("\t\t\t\t\t\t");
      out.print(id);
      out.write("</p></li>\r\n");
      out.write("\t\t\t\t<li class=\"smaller cursor ml-2\"><a href=\"log-out\" class=\"a\"><i\r\n");
      out.write("\t\t\t\t\t\tclass=\"fas fa-sign-out-alt mr-1 text-danger\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"font-size: 20px;\"></i>Đăng xuất</a></li>\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\t<script src=\"bootstrap/js/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("\t<script src=\"bootstrap/js/bootstrap.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write('\r');
      out.write('\n');
      out.write('	');

		funct f = new funct();
	
      out.write("\r\n");
      out.write("\t<div class=\"my-4\">\r\n");
      out.write("\t\t");

			ArrayList<SachBean> listSach = null;
			int index = 0, countPage = 0;
			if (request.getAttribute("listSach") != null) {
				listSach = (ArrayList<SachBean>) request.getAttribute("listSach");
				index = Integer.parseInt(request.getAttribute("page").toString());
				countPage = Integer.parseInt(request.getAttribute("countPage").toString());
			}
		
      out.write("\r\n");
      out.write("\t\t<div class=\"row\" style=\"background-color: #f0f0f0; margin: 0 6rem;\">\r\n");
      out.write("\t\t\t<div class=\"col-md-3 bg-light\">\r\n");
      out.write("\t\t\t\t<ul class=\"category p-0 m-0 \" style=\"width: 100%;\">\r\n");
      out.write("\t\t\t\t\t");

						ArrayList<loaiBean> listLoai = null;
						if (request.getAttribute("listLoai") != null) {
							listLoai = (ArrayList<loaiBean>) request.getAttribute("listLoai");
							for (loaiBean loai : listLoai) {
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<li class=\"lk\"><a\r\n");
      out.write("\t\t\t\t\t\thref=\"");
      out.print("category?ma=" + loai.getMaLoai());
      out.write("\"><div\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"py-1 pl-3\" style=\"width: 100%;\">");
      out.print(loai.getTenLoai());
      out.write("</div></a></li>\r\n");
      out.write("\t\t\t\t\t");

						}
						}
					
      out.write("\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-9 px-0\">\r\n");
      out.write("\t\t\t\t<div class=\"py-2 bg-light\" style=\"width: 100%;\">\r\n");
      out.write("\t\t\t\t\t<p class=\"text-danger m-0 ml-5\">\r\n");
      out.write("\t\t\t\t\t\tCó:\r\n");
      out.write("\t\t\t\t\t\t");
      out.print(request.getAttribute("countItems") != null ? request.getAttribute("countItems") : 0);
      out.write("\r\n");
      out.write("\t\t\t\t\t\tkết quả.\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"px-4 py-2\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\" style=\"min-height: 52vh;\">\r\n");
      out.write("\t\t\t\t\t\t");

							if (listSach != null) {
								for (SachBean sach : listSach) {
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-3 col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card my-3 bg-light cursor\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"min-height: 500px;; width: 100%;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"card-link\" href=\"");
      out.print("sach_detail?ms=" + sach.getMasach());
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t <img alt=\"\" src=\"");
      out.print(sach.getAnh());
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"width: 100%; min-height: 290px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"p-1 mt-2  mx-3 \" style=\"min-height: 70px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p class=\"m-0 font-weight-bold\">");
      out.print(sach.getTensach());
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"p-1 mx-3\" style=\"min-height: 50px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p class=\"m-0\">");
      out.print(sach.getTacgia());
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h6 class=\"p-1 text-danger font-weight-bold ml-3\">");
      out.print(f.formart(sach.getGia()));
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tđ\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a> <a class=\"p-1 text-success font-weight-bold smaller ml-3\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"");
      out.print("cart?c=th&ms=" + sach.getMasach());
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"cursor: pointer;\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"fas fa-cart-plus text-warning\"></i> Thêm vào giỏ</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t");

							}
								int pre = index == 1 ? 1 : (index - 1);
								int next = index == countPage ? countPage : (index + 1);
								int start = index == 1 ? 1 : (index - 1);
								start = (index == countPage) && (index >= 3) ? index - 3 + 1 : start;
								int end = index == countPage ? countPage : (index + 1);
								end = (end - start + 1 < 3) && (end != countPage) ? start + 2 : end;

								String url1 = null;
								String url2 = null;
								String ma = null;
								String type = request.getAttribute("type").toString();
								switch (type) {
								case "home":
									url1 = "home?page=" + pre;
									url2 = "home?page=" + next;
									break;
								case "loai":
									ma = request.getAttribute("ma").toString();
									url1 = "category?ma=" + ma + "&page=" + pre;
									url2 = "category?ma=" + ma + "&page=" + next;
									break;
								default:
									key = request.getAttribute("key").toString();
									url1 = "search?key=" + key + "&page=" + pre;
									url2 = "search?key=" + key + "&page=" + next;
									break;
								}
								if (countPage > 0) {
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<nav class=\"mt-3\" aria-label=\"Page navigation example\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"width: 100%;\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"page mt-2 mb-3\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"width: 20%; margin: auto; text-align: center;\">\r\n");
      out.write("\t\t\t\t\t\t\t\tTrang <span class=\"text-danger font-weight-bold\">");
      out.print(index);
      out.write("</span>/\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      out.print(countPage);
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"pagination d-flex justify-content-center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"page-item\"><a class=\"page-link text-dark\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"");
      out.print(url1);
      out.write("\" aria-label=\"Previous\"> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\taria-hidden=\"true\">&laquo;</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									if (type.trim().equals("home")) {
												for (int i = start; i <= end; i++) {
								
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"page-item\"><a class=\"page-link text-dark\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"");
      out.print("home?page=" + i);
      out.write('"');
      out.write('>');
      out.print(i);
      out.write("</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									}
											} else if (type.trim().equals("loai")) {

												for (int i = start; i <= end; i++) {
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"page-item\"><a class=\"page-link text-dark\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"");
      out.print("category?ma=" + ma + "&page=" + i);
      out.write('"');
      out.write('>');
      out.print(i);
      out.write("</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									}
											} else {

												for (int i = start; i <= end; i++) {
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"page-item\"><a class=\"page-link text-dark\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"");
      out.print("search?key=" + key + "&page=" + i);
      out.write('"');
      out.write('>');
      out.print(i);
      out.write("</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									}
											}
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"page-item\"><a class=\"page-link text-dark\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"");
      out.print(url2);
      out.write("\" aria-label=\"Next\"> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\taria-hidden=\"true\">&raquo;</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</nav>\r\n");
      out.write("\t\t\t\t\t\t");

							}
							}
						
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://fonts.googleapis.com/css2?family=Poppins&display=swap\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<script src=\"https://kit.fontawesome.com/7e31e7a48c.js\"\r\n");
      out.write("\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/Footer.css\">\r\n");
      out.write("<title>footer</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<footer style=\"background-color: #EDEAEA;\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-md-2\"></div>\r\n");
      out.write("\t\t\t<div class=\"col mt-4\">\r\n");
      out.write("\t\t\t\t<p class=\"footer-link\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\">Giới thiệu về công ty</a>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<p class=\"footer-link\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\">Câu hỏi thường gặp mua hàng</a>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<p class=\"footer-link\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\">Chính sách bảo mật</a>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<p class=\"footer-link\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\">Quy chế hoạt động</a>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<p class=\"footer-link\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\">Kiểm tra hóa đơn điện tử</a>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<p class=\"footer-link\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\">Tra cứu thông tin bảo hành</a>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col mt-4\">\r\n");
      out.write("\t\t\t\t<p class=\"footer-link\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\">Tin tuyển dụng</a>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<p class=\"footer-link\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\">Tin khuyến mãi</a>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<p class=\"footer-link\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\">Hướng dẫn mua online</a>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<p class=\"footer-link\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\">Hướng dẫn mua trả góp</a>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<p class=\"footer-link\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\">Chính sách trả góp</a>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col mt-4\">\r\n");
      out.write("\t\t\t\t<p class=\"footer-link\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\">Hệ thống cửa hàng</a>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<p class=\"footer-link\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\">Hệ thống bảo hành</a>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<p class=\"footer-link\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\">Kiểm tra hàng Apple chính hãng</a>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<p class=\"footer-link\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\">Giới thiệu máy đổi trả</a>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<p class=\"footer-link\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\">Chính sách đổi trả</a>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col mt-4\">\r\n");
      out.write("\t\t\t\t<p class=\"smaller m-0\">Tư vấn mua hàng (Miễn phí)</p>\r\n");
      out.write("\t\t\t\t<h5 class=\"text-danger\">1800 6601</h5>\r\n");
      out.write("\t\t\t\t<p class=\"font-weight-bold m-0\">Hỗ trợ thanh toán:</p>\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<span><i class=\"fab fa-cc-visa fa-2x text-danger\"></i></span> <span><i\r\n");
      out.write("\t\t\t\t\t\tclass=\"far fa-credit-card fa-2x text-warning\"></i></span> <span><i\r\n");
      out.write("\t\t\t\t\t\tclass=\"fab fa-cc-mastercard fa-2x text-info\"></i></span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col mt-4\">\r\n");
      out.write("\t\t\t\t<p class=\"smaller m-0\">Góp ý, khiếu nại dịch vụ (8h00-22h00)</p>\r\n");
      out.write("\t\t\t\t<h5 class=\"text-danger\">1800 6616</h5>\r\n");
      out.write("\t\t\t\t<p class=\"font-weight-bold m-0 mb-1\">Liên hệ:</p>\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<span><i\r\n");
      out.write("\t\t\t\t\t\tclass=\"fab fa-facebook-square fa-2x text-primary mr-1\"></i></span> <span><i\r\n");
      out.write("\t\t\t\t\t\tclass=\"fab fa-instagram fa-2x text-danger mr-1\"></i></span> <span><i\r\n");
      out.write("\t\t\t\t\t\tclass=\"fab fa-twitter-square fa-2x text-info\"></i></span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-2\"></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"copyright text-center\">\r\n");
      out.write("\t\t\t<p class=\"m-0 py-2\">© 2007 - 2020 Công Ty Cổ Phần Bán Lẻ Kỹ Thuật\r\n");
      out.write("\t\t\t\tSố FPT / Địa chỉ: 261 - 263 Khánh Hội, P5, Q4, TP. Hồ Chí Minh /\r\n");
      out.write("\t\t\t\tGPĐKKD số 0311609355 do Sở KHĐT TP.HCM cấp ngày 08/03/2012. GP số\r\n");
      out.write("\t\t\t\t47/GP-TTĐT do sở TTTT TP HCM cấp ngày 02/07/2018. Điện thoại:\r\n");
      out.write("\t\t\t\t(028)73023456. Email: fptshop@fpt.com.vn. Chịu trách nhiệm nội dung:\r\n");
      out.write("\t\t\t\tNguyễn Trịnh Nhật Linh.</p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
