/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.58
 * Generated at: 2020-11-22 13:19:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class sign_002din_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"bootstrap/css/bootstrap.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"bootstrap/css/bootstrap.min.css\">\r\n");
      out.write("<link href=\"fontawesome/css/fontawesome.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"fontawesome/css/brands.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"fontawesome/css/solid.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"css/Login.css\" rel=\"stylesheet\">\r\n");
      out.write("<title>Sign in</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"login d-flex justify-content-center\" style=\"height: auto;\">\r\n");
      out.write("\t\t<div class=\"my-5\">\r\n");
      out.write("\t\t\t");

				String[] warnings = null;
				if (request.getAttribute("warning") != null) {
					warnings = (String[]) request.getAttribute("warning");
				}
				if (warnings != null) {
					for (String warning : warnings) {
			
      out.write("\r\n");
      out.write("\t\t\t<div class=\"alert alert-danger\" role=\"alert\">\r\n");
      out.write("\t\t\t\t");
      out.print(warning);
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t");

				}
				}
			
      out.write("\r\n");
      out.write("\t\t\t<div class=\"card mt-0\" style=\"height: 760px;\">\r\n");
      out.write("\t\t\t\t<div class=\"card-header bg-dark\">\r\n");
      out.write("\t\t\t\t\t<h3>Đăng ký</h3>\r\n");
      out.write("\t\t\t\t\t<div class=\"d-flex justify-content-end social_icon\">\r\n");
      out.write("\t\t\t\t\t\t<span><i class=\"fab fa-facebook-square smaller text-light\"></i></span>\r\n");
      out.write("\t\t\t\t\t\t<span><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"fab fa-google-plus-square smaller text-light\"></i></span> <span><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"fab fa-twitter-square smaller text-light\"></i></span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"p-4\">\r\n");
      out.write("\t\t\t\t\t<form action=\"sign-in\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"exampleInputEmail1\">Họ tên:</label> <input\r\n");
      out.write("\t\t\t\t\t\t\t\ttype=\"text\" class=\"form-control\" id=\"exampleInputEmail1\"\r\n");
      out.write("\t\t\t\t\t\t\t\taria-describedby=\"emailHelp\" name=\"fullname\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"Nhập họ tên.\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"exampleInputEmail1\">Địa chỉ:</label> <input\r\n");
      out.write("\t\t\t\t\t\t\t\ttype=\"text\" class=\"form-control\" id=\"exampleInputEmail1\"\r\n");
      out.write("\t\t\t\t\t\t\t\taria-describedby=\"emailHelp\" name=\"address\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"Nhập địa chỉ.\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"exampleInputEmail1\">SĐT:</label> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"form-control\" id=\"exampleInputEmail1\"\r\n");
      out.write("\t\t\t\t\t\t\t\taria-describedby=\"emailHelp\" name=\"phone\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"Nhập SĐT.\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"exampleInputEmail1\">Email:</label> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"form-control\" id=\"exampleInputEmail1\"\r\n");
      out.write("\t\t\t\t\t\t\t\taria-describedby=\"emailHelp\" name=\"email\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"Nhập Email.\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"exampleInputEmail1\">Tên tên đăng nhập:</label> <input\r\n");
      out.write("\t\t\t\t\t\t\t\ttype=\"text\" class=\"form-control\" id=\"exampleInputEmail1\"\r\n");
      out.write("\t\t\t\t\t\t\t\taria-describedby=\"emailHelp\" name=\"username\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"Nhập username.\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"exampleInputPassword1\">Mật khẩu:</label> <input\r\n");
      out.write("\t\t\t\t\t\t\t\ttype=\"password\" class=\"form-control\" id=\"exampleInputPassword1\"\r\n");
      out.write("\t\t\t\t\t\t\t\tname=\"pass\" placeholder=\"Nhập mật khẩu.\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"exampleInputPassword1\">Nhập lại mật khẩu:</label> <input\r\n");
      out.write("\t\t\t\t\t\t\t\ttype=\"password\" class=\"form-control\" id=\"exampleInputPassword1\"\r\n");
      out.write("\t\t\t\t\t\t\t\tname=\"repass\" placeholder=\"Nhập lại mật khẩu.\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" class=\"btn btn-dark\" value=\"Đăng ký\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"mt-3 mr-3\" style=\"float: right;\"><a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"login\" style=\"color: #0E80D7; font-size: smaller;\">Trở\r\n");
      out.write("\t\t\t\t\t\t\t\tvề<i class=\"fas fa-undo ml-2\"></i>\r\n");
      out.write("\t\t\t\t\t\t</a></span>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<script src=\"bootstrap/js/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("\t<script src=\"bootstrap/js/bootstrap.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
