/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.58
 * Generated at: 2020-11-10 02:53:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class DangNhap_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width\" />\r\n");
      out.write("    <title>Index</title>\r\n");
      out.write("\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"author\" content=\"\">\r\n");
      out.write("    <title>Shop Homepage - Start Bootstrap Template</title>\r\n");
      out.write("    <!-- Bootstrap Core CSS -->\r\n");
      out.write("    <link href=\"Content/bootstrap.css\" rel=\"stylesheet\" />\r\n");
      out.write("\r\n");
      out.write("    <!-- Custom CSS -->\r\n");
      out.write("    <link href=\"Content/shop-homepage.css\" rel=\"stylesheet\" />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->\r\n");
      out.write("    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\r\n");
      out.write("    <!--[if lt IE 9]>\r\n");
      out.write("        <script src=\"https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js\"></script>\r\n");
      out.write("        <script src=\"https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js\"></script>\r\n");
      out.write("    <![endif]-->\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- Navigation -->\r\n");
      out.write("    <nav class=\"navbar navbar-inverse navbar-fixed-top\" role=\"navigation\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <!-- Brand and toggle get grouped for better mobile display -->\r\n");
      out.write("            <div class=\"navbar-header\">\r\n");
      out.write("                <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#bs-example-navbar-collapse-1\">\r\n");
      out.write("                    <span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("                    <span class=\"icon-bar\"></span>\r\n");
      out.write("                    <span class=\"icon-bar\"></span>\r\n");
      out.write("                    <span class=\"icon-bar\"></span>\r\n");
      out.write("                </button>\r\n");
      out.write("                <a class=\"navbar-brand\" href=\"#\">Start Bootstrap</a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- Collect the nav links, forms, and other content for toggling -->\r\n");
      out.write("            <div class=\"collapse navbar-collapse\" id=\"bs-example-navbar-collapse-1\">\r\n");
      out.write("                <ul class=\"nav navbar-nav\">\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"/BookStore\">TRANG CHỦ</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"/Nguoidung/Dangky\">ĐĂNG K&#221;</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"/Nguoidung/Dangnhap\">ĐĂNG NHẬP</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"/Giohang/Giohang\" style=\"color: white; font-weight: bold; text-decoration: none;\">\r\n");
      out.write("                            <img src=\"images/giohang.gif\" />Giỏ Hàng (0)\r\n");
      out.write("                        </a>\r\n");
      out.write("\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- /.navbar-collapse -->\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- /.container -->\r\n");
      out.write("    </nav>\r\n");
      out.write("    <!-- Page Content -->\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-md-3\">\r\n");
      out.write("\r\n");
      out.write("                <p class=\"lead\"> CHỦ ĐỀ SÁCH</p>\r\n");
      out.write("                <div class=\"list-group\">\r\n");
      out.write("                    <a href=\"/BookStore/SPTheochude/1\" class=\"list-group-item\">\r\n");
      out.write("                        Ngoại ngữ\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a href=\"/BookStore/SPTheochude/2\" class=\"list-group-item\">\r\n");
      out.write("                        C&#244;ng nghệ th&#244;ng tin\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a href=\"/BookStore/SPTheochude/3\" class=\"list-group-item\">\r\n");
      out.write("                        Luật\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a href=\"/BookStore/SPTheochude/4\" class=\"list-group-item\">\r\n");
      out.write("                        Văn học\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a href=\"/BookStore/SPTheochude/5\" class=\"list-group-item\">\r\n");
      out.write("                        Khoa học kỹ thuật\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a href=\"/BookStore/SPTheochude/6\" class=\"list-group-item\">\r\n");
      out.write("                        N&#244;ng nghiệp\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a href=\"/BookStore/SPTheochude/7\" class=\"list-group-item\">\r\n");
      out.write("                        Triết học-Ch&#237;nh trị\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a href=\"/BookStore/SPTheochude/8\" class=\"list-group-item\">\r\n");
      out.write("                        Lịch sử, địa l&#253;\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a href=\"/BookStore/SPTheochude/9\" class=\"list-group-item\">\r\n");
      out.write("                        Kinh tế\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a href=\"/BookStore/SPTheochude/10\" class=\"list-group-item\">\r\n");
      out.write("                        S&#225;ch gi&#225;o khoa\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a href=\"/BookStore/SPTheochude/11\" class=\"list-group-item\">\r\n");
      out.write("                        Nghệ thuật sống\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <p class=\"lead\"> NHÀ XUẤT BẢN </p>\r\n");
      out.write("                <div class=\"list-group\">\r\n");
      out.write("                    <a href=\"/BookStore/SPTheoNXB/1\" class=\"list-group-item\">\r\n");
      out.write("                        Nh&#224; xuất bản Trẻ\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a href=\"/BookStore/SPTheoNXB/2\" class=\"list-group-item\">\r\n");
      out.write("                        NXB Thống k&#234;\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a href=\"/BookStore/SPTheoNXB/3\" class=\"list-group-item\">\r\n");
      out.write("                        Kim đồng\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a href=\"/BookStore/SPTheoNXB/4\" class=\"list-group-item\">\r\n");
      out.write("                        Đại học quốc gia\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a href=\"/BookStore/SPTheoNXB/5\" class=\"list-group-item\">\r\n");
      out.write("                        Văn h&#243;a nghệ thuật\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a href=\"/BookStore/SPTheoNXB/6\" class=\"list-group-item\">\r\n");
      out.write("                        Văn h&#243;a\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a href=\"/BookStore/SPTheoNXB/7\" class=\"list-group-item\">\r\n");
      out.write("                        Lao động - X&#227; hội\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a href=\"/BookStore/SPTheoNXB/8\" class=\"list-group-item\">\r\n");
      out.write("                        Khoa Học &amp; Kỹ Thuật\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-9\">\r\n");
      out.write("                <div class=\"row carousel-holder\">\r\n");
      out.write("                    <div class=\"col-md-12\">\r\n");
      out.write("                        <div id=\"carousel-example-generic\" class=\"carousel slide\" data-ride=\"carousel\">\r\n");
      out.write("                            <ol class=\"carousel-indicators\">\r\n");
      out.write("                                <li data-target=\"#carousel-example-generic\" data-slide-to=\"0\" class=\"active\"></li>\r\n");
      out.write("                                <li data-target=\"#carousel-example-generic\" data-slide-to=\"1\"></li>\r\n");
      out.write("                                <li data-target=\"#carousel-example-generic\" data-slide-to=\"2\"></li>\r\n");
      out.write("                            </ol>\r\n");
      out.write("                            <div class=\"carousel-inner\">\r\n");
      out.write("                                <div class=\"item active\">\r\n");
      out.write("                                    <img class=\"slide-image\" src=\"images/ancient-place.jpg\" alt=\"\">\r\n");
      out.write("\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"item\">\r\n");
      out.write("                                    <img class=\"slide-image\" src=\"images/riverside-city.jpg\" alt=\"\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"item\">\r\n");
      out.write("                                    <img class=\"slide-image\" src=\"images/kayaks.jpg\" alt=\"\">\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <a class=\"left carousel-control\" href=\"#carousel-example-generic\" data-slide=\"prev\">\r\n");
      out.write("                                <span class=\"glyphicon glyphicon-chevron-left\"></span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <a class=\"right carousel-control\" href=\"#carousel-example-generic\" data-slide=\"next\">\r\n");
      out.write("                                <span class=\"glyphicon glyphicon-chevron-right\"></span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <h4 style=\"color:red; text-align:center\"> </h4>\r\n");
      out.write("                    <h3 style=\"text-align:center\">ĐĂNG NHẬP</h3><table align=\"center\">\r\n");
      out.write("\r\n");
      out.write("                        <form action=\"/Nguoidung/Dangnhap\" method=\"post\"></form>\r\n");
      out.write("                        <tbody>\r\n");
      out.write("                            <tr style=\"height:40px\">\r\n");
      out.write("                                <td> Tên đăng nhật:</td>\r\n");
      out.write("                                <td>\r\n");
      out.write("                                    <input id=\"TenDN\" name=\"TenDN\" type=\"text\" value=\"\">\r\n");
      out.write("\r\n");
      out.write("                                </td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr style=\"height:40px\">\r\n");
      out.write("                                <td align=\"right\">  Mật khẩu:</td>\r\n");
      out.write("                                <td>\r\n");
      out.write("                                    <input id=\"Matkhau\" name=\"Matkhau\" type=\"password\">\r\n");
      out.write("\r\n");
      out.write("                                </td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr style=\"height:40px\">\r\n");
      out.write("                                <td></td>\r\n");
      out.write("                                <td>\r\n");
      out.write("                                    <input type=\"Submit\" value=\"Đăng nhập\">\r\n");
      out.write("                                </td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        </tbody>\r\n");
      out.write("                    </table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- /.container -->\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <hr>\r\n");
      out.write("        <!-- Footer -->\r\n");
      out.write("        <footer>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-12\">\r\n");
      out.write("                    <p>Copyright &copy; MVC 5</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </footer>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- /.container -->\r\n");
      out.write("    <!-- jQuery -->\r\n");
      out.write("    <script src=\"/Scripts/jquery.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap Core JavaScript -->\r\n");
      out.write("    <script src=\"/Scripts/bootstrap.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
